package enigma.engine.regex;

public enum InstructionAction {
	PRINT_INSTRUCTION,
	UNLOCKREGEX,
	LOCKREGEX,
	DRAW_STRING_MATCHES,
	HIGHLIGHT,
	SET_KBUTTON_FLAG_FALSE,
	DRAW_LAMBDA,
	STRING_LENGTH_ATLEAST_MINSIZE,
	LOAD_NEXT
}
